/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp cn.kylinos.Kmre.FileWatcher.xml -a file_watcher_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef FILE_WATCHER_ADAPTOR_H
#define FILE_WATCHER_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface cn.kylinos.Kmre.FileWatcher
 */
class FileWatcherAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "cn.kylinos.Kmre.FileWatcher")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"cn.kylinos.Kmre.FileWatcher\">\n"
"    <method name=\"start\"/>\n"
"    <method name=\"stop\"/>\n"
"  </interface>\n"
        "")
public:
    FileWatcherAdaptor(QObject *parent);
    virtual ~FileWatcherAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void start();
    void stop();
Q_SIGNALS: // SIGNALS
};

#endif
