/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp cn.kylinos.Kmre.Audio.xml -a audio_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "audio_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AudioAdaptor
 */

AudioAdaptor::AudioAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AudioAdaptor::~AudioAdaptor()
{
    // destructor
}

void AudioAdaptor::start()
{
    // handle method call cn.kylinos.Kmre.Audio.start
    QMetaObject::invokeMethod(parent(), "start");
}

void AudioAdaptor::stop()
{
    // handle method call cn.kylinos.Kmre.Audio.stop
    QMetaObject::invokeMethod(parent(), "stop");
}

