/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp cn.kylinos.Kmre.Manager.xml -i metatypes.h -a kmre_manager
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KMRE_MANAGER_H
#define KMRE_MANAGER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "metatypes.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface cn.kylinos.Kmre.Manager
 */
class ManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "cn.kylinos.Kmre.Manager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"cn.kylinos.Kmre.Manager\">\n"
"    <method name=\"quit\"/>\n"
"    <method name=\"closeApp\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"pkgName\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"forceKill\"/>\n"
"    </method>\n"
"    <method name=\"getDisplayInformation\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"info\"/>\n"
"    </method>\n"
"    <method name=\"controlApp\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"pkgName\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"event_type\"/>\n"
"    </method>\n"
"    <method name=\"setSystemProp\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"event_type\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value_field\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"getSystemProp\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"event_type\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value_field\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"addOneRecord\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"mime_type\"/>\n"
"    </method>\n"
"    <method name=\"removeOneRecord\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"mime_type\"/>\n"
"    </method>\n"
"    <method name=\"commandToGetAllFiles\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"filesIsEmpty\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"ret\"/>\n"
"    </method>\n"
"    <method name=\"getAllFiles\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"uri\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"reverse\"/>\n"
"      <arg direction=\"out\" type=\"a(ss)\" name=\"result\"/>\n"
"      <annotation value=\"AndroidMetaList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"isHostSupportDDS\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"setCameraDevice\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"device\"/>\n"
"    </method>\n"
"    <method name=\"getCameraDevice\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"device\"/>\n"
"    </method>\n"
"    <signal name=\"filesMessage\">\n"
"      <arg type=\"i\" name=\"type\"/>\n"
"      <arg type=\"a(ss)\" name=\"metas\"/>\n"
"      <annotation value=\"AndroidMetaList\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </signal>\n"
"    <signal name=\"currentCameraDevice\">\n"
"      <arg type=\"s\" name=\"deviceName\"/>\n"
"    </signal>\n"
"    <signal name=\"appSeparationStateChanged\">\n"
"      <arg type=\"s\" name=\"pkgName\"/>\n"
"      <arg type=\"b\" name=\"enable\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ManagerAdaptor(QObject *parent);
    virtual ~ManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addOneRecord(const QString &path, const QString &mime_type);
    void closeApp(const QString &appName, const QString &pkgName, bool forceKill);
    void commandToGetAllFiles(int type);
    void controlApp(int id, const QString &pkgName, int event_type);
    bool filesIsEmpty();
    AndroidMetaList getAllFiles(const QString &uri, bool reverse);
    QString getCameraDevice();
    QString getDisplayInformation();
    QString getSystemProp(int event_type, const QString &value_field);
    bool isHostSupportDDS();
    void quit();
    void removeOneRecord(const QString &path, const QString &mime_type);
    void setCameraDevice(const QString &device);
    void setSystemProp(int event_type, const QString &value_field, const QString &value);
Q_SIGNALS: // SIGNALS
    void appSeparationStateChanged(const QString &pkgName, bool enable);
    void currentCameraDevice(const QString &deviceName);
    void filesMessage(int type, AndroidMetaList metas);
};

#endif
